<?php

return [
    '/' => 'controllers/index.php',
    '/student' => 'controllers/student.php',
    '/student/profile' => 'controllers/student-profile.php',
    '/student/profile/edit' => 'controllers/student-profile-edit.php',
    '/student/internships' => 'controllers/student-internship.php',
    '/student/internships/view' => 'controllers/student-internship-view.php',
    '/student/internships/apply' => 'controllers/student-internship-application.php',
    '/student/applications' => 'controllers/student-applications.php',
    '/student/notifications' => 'controllers/student-notifications.php',
    '/login' => 'controllers/login.php',
    '/login/authenticate' => 'controllers/login-process.php',
    '/logout' => 'controllers/logout.php',
    '/register' => 'controllers/register.php',
    '/admin' => 'controllers/admin.php',
    '/admin/manage' => 'controllers/admin-manage.php',
    '/admin/login' => 'controllers/admin-login.php',
    '/admin/register' => 'controllers/admin-register.php',
    '/admin/students' => 'controllers/admin-students.php',
    '/admin/students/view' => 'controllers/admin-students-view.php',
    '/admin/applications' => 'controllers/admin-applications.php',
    '/admin/applications/view' => 'controllers/admin-applications-view.php',
    '/admin/applications/action' => 'controllers/admin-applications-action.php',
    '/admin/internships' => 'controllers/admin-internships.php',
    '/admin/internships/create' => 'controllers/admin-internships-create.php',
    '/admin/internships/view' => 'controllers/admin-internships-view.php',
    '/admin/internships/edit' => 'controllers/admin-internships-edit.php',
    '/admin/internships/delete' => 'controllers/admin-internships-delete.php',
];